package view;

/**
 *
 * @author Fernando César
 */
public class Sobre extends javax.swing.JFrame {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSobre = new javax.swing.JLabel();
        labelDesenvolvedores = new javax.swing.JLabel();
        labelFernando = new javax.swing.JLabel();
        labelLuis = new javax.swing.JLabel();
        labelIDEs = new javax.swing.JLabel();
        labelNetbeans = new javax.swing.JLabel();
        labelMySQL = new javax.swing.JLabel();
        labelPhotoshop = new javax.swing.JLabel();
        labelBiblioteca = new javax.swing.JLabel();
        labelJava = new javax.swing.JLabel();
        labelDriver = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sobre");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/carro-icon.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        labelSobre.setForeground(new java.awt.Color(255, 255, 255));
        labelSobre.setText("Sobre Estacionamento v2.0:");

        labelDesenvolvedores.setForeground(new java.awt.Color(255, 255, 255));
        labelDesenvolvedores.setText("Desenvolvedores:");

        labelFernando.setForeground(new java.awt.Color(255, 255, 255));
        labelFernando.setText("Fernando César dos Santos");

        labelLuis.setForeground(new java.awt.Color(255, 255, 255));
        labelLuis.setText("Luís Henrique Turani");

        labelIDEs.setForeground(new java.awt.Color(255, 255, 255));
        labelIDEs.setText("IDEs:");

        labelNetbeans.setForeground(new java.awt.Color(255, 255, 255));
        labelNetbeans.setText("NetBeans 8.2");

        labelMySQL.setForeground(new java.awt.Color(255, 255, 255));
        labelMySQL.setText("MySQL Workbench");

        labelPhotoshop.setForeground(new java.awt.Color(255, 255, 255));
        labelPhotoshop.setText("Photoshop CC 2015");

        labelBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        labelBiblioteca.setText("Biblioteca:");

        labelJava.setForeground(new java.awt.Color(255, 255, 255));
        labelJava.setText("Java 8.0");

        labelDriver.setForeground(new java.awt.Color(255, 255, 255));
        labelDriver.setText("Driver JDBC do MySQL 5.1.23");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Voltar.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Funcionalidades:\n\nÉ possível armazenar até 30 clientes em 30 \nvagas diferentes.\n\nO usuário pode alterar ID e Senha de acesso, porém,\npor segurança apenas há a possibilidade de haver 1\ncadastro de usuário, então um ID e senha por vez.\n\nPode ser feito apenas o cadastro e remoção, edição\nnão é possível.\n\nOs cadastros são únicos, possuem um ID que nunca irá\nse repetir.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSobre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDesenvolvedores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLuis)
                                    .addComponent(labelFernando)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelIDEs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMySQL)
                                    .addComponent(labelNetbeans)
                                    .addComponent(labelPhotoshop)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelBiblioteca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDriver)
                                    .addComponent(labelJava))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSobre)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesenvolvedores)
                    .addComponent(labelFernando))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLuis)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIDEs)
                    .addComponent(labelNetbeans))
                .addGap(4, 4, 4)
                .addComponent(labelMySQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPhotoshop)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBiblioteca)
                    .addComponent(labelJava))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDriver)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FramePrincipal f = new FramePrincipal();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelBiblioteca;
    private javax.swing.JLabel labelDesenvolvedores;
    private javax.swing.JLabel labelDriver;
    private javax.swing.JLabel labelFernando;
    private javax.swing.JLabel labelIDEs;
    private javax.swing.JLabel labelJava;
    private javax.swing.JLabel labelLuis;
    private javax.swing.JLabel labelMySQL;
    private javax.swing.JLabel labelNetbeans;
    private javax.swing.JLabel labelPhotoshop;
    private javax.swing.JLabel labelSobre;
    // End of variables declaration//GEN-END:variables
}
